### ISSUE TITLE
Audio Streaming

### ISSUE THREAD

**Issue by VideahGams** [VideahGams/LovePotion#53]
At the moment a lot of people are having issues with running out of linear memory, having the option to stream music rather than load it all at once should fix that.

**Comment by Substance12** [comment]
I second this.

**Comment by Blaize-Murad** [comment]
This would be a great feature! If this ends up being implemented i'll make a media center for sure

**Comment by Reuh** [comment]
I've just added streaming to ctrµLua: [here](https://github.com/ctruLua/ctruLua/commit/6ac83ca6dfbb3b0d4df03db544cbc1eb5a8e764d) and [here](https://github.com/ctruLua/ctruLua/commit/4c9bdf75fae28c5dc630fb0770fe1e3206b1be83).

I was going to create a pull request where I copy-paste ctrµLua's code into LövePotion, but then I realized it would need a bit more work. The backend is fine, but it's not really like Löve's API and require some changes (notably the fact that ctrµLua's audio objects can be played more than once at a time, so this has to be removed to stick with Löve's API - the code should actually be simpler without this feature).
I may do this if I have some time, but if you feel like it it shouldn't be too hard to adapt the code.


(also, it's not really related to the issue, but since most of ctrµLua's code which is in LövePotion was made by me, would you mind adding in the ctrµLua's line of the credits section "Reuh" instead of "and everyone who worked on"? :p)

**Comment by VideahGams** [comment]
Nice, this makes life a lot easier! I'll have a look over it soon and see if I can implement it here. (and sure, I'll make sure to credit everyone individually :P)

**Comment by Xavyrr** [comment]
I get that sticking to the LOVE API makes sense but wouldn't it be better to allow overlapping sound effects? I think it's silly to do more work to add a limitation.

**Comment by VideahGams** [comment]
It's not really a limitation, it's just how it's designed.
I will try [implement this soon](https://www.love2d.org/wiki/Source:clone) as that's the prefered way of playing the same sound more than once.

**Comment by Xavyrr** [comment]
Ah, awesome. BTW, it seems like loading a specific sound (a bgm) it autoplays and loops despite not being told to. It also seems to start playback at the end of a sound effect played prior's length. Though it doesn't seem like to big an issue, I'm messing with it now to narrow down what's causing it. I'll try an .ogg

**Comment by Xavyrr** [comment]
Hmm, no dice. Also this glitchy playback doesn't respond to love.audio:stop() or source:stop(). Weird. At least it runs though <3

**Comment by TurtleP** [comment]
I got this to work based on the ctrulua code, although much more optimal. Only issue right now is the automatic buffer filling has gaps between loads.

**Comment by TurtleP** [comment]
Coming soon when I have it fully working! It auto loads the data in the background like LOVE does, but it's still a bit off. I'm closing this for now, and expect the push soon (Ogg Vorbis only).
