### ISSUE TITLE
dt is calculated wrong during/right after launching a game

### ISSUE THREAD

**Issue by Xavyrr** [VideahGams/LovePotion#56]
My LovePotion game has several states. the first which is based on a timer. When launched from HBL it displays animated visual artifacts on the left side, plays a sound that should play, and skips over all of the drawing for the step and goes to the next state almost immediately, when it should wait about 10-15 seconds. When installed from a .cia, it throws an error for the sound, stating that it's a nil value. I remove the sound references, and it skips the first state in a similar manner to the HBL version, except with no visual glitches (and no sound since it was removed). In both instances, when re executing that code, it runs exactly like it is intended. I did not have the issue on 10.3 firmware, and *hax updated to 2.7 a few days ago which I assumed was the issue, but it persists similarly with the cia version, so I'm not sure if this is a 10.7 issue (I just installed A9LH on sysNAND and updated to 10.7 on my O3DS).

EDIT: I thought maybe there was something wrong with dt, so I threw up a test timer, and the code for it was 
timer= timer+dt 
so I printed it and right after launching, it's over 530,000, but counts normally afterwards.

**Comment by kitling** [comment]
So far as I can tell, this is a bug with the first time the `love.timer.step()` function is called. Because it hasn't been called before, the previous time it has stored is likely set to 0... and when compared to a large positive value from `osGetTime()` because the time isn't near 0, we get this large value in our delta time. The way to fix this would be to call `love.timer.step()` once when you are initializing stuff, or otherwise initialize the previous time that it uses.
